# Generated by Django 4.1.7 on 2023-04-26 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Matricula', models.CharField(max_length=11, null=True)),
                ('Nome', models.CharField(max_length=100, null=True)),
                ('Coluna1', models.CharField(max_length=100, null=True)),
                ('AdmissaoData', models.CharField(max_length=45, null=True)),
                ('Login', models.CharField(max_length=45, null=True)),
                ('Cpf', models.IntegerField(null=True)),
                ('Email', models.CharField(max_length=200, null=True)),
                ('NascimentoData', models.DateTimeField(null=True)),
                ('Cargo', models.CharField(max_length=100, null=True)),
                ('CargoCodigo', models.CharField(max_length=45, null=True)),
                ('SalarioRef', models.CharField(max_length=25, null=True)),
                ('Funcao', models.CharField(max_length=100, null=True)),
                ('FuncaoCodigo', models.CharField(max_length=45, null=True)),
                ('FuncaoRef', models.CharField(max_length=45, null=True)),
                ('UA', models.CharField(max_length=45, null=True)),
                ('LotacaoCod', models.CharField(max_length=20, null=True)),
                ('LotacaoDesc', models.CharField(max_length=100, null=True)),
                ('LotacaoSigla', models.CharField(max_length=10, null=True)),
                ('Status', models.CharField(max_length=45, null=True)),
                ('Data_afastamento', models.DateTimeField(null=True)),
                ('AfastamentoMotivo', models.CharField(max_length=100, null=True)),
                ('PDV', models.IntegerField(null=True)),
                ('Sexo', models.CharField(max_length=45, null=True)),
                ('Data_desligamento', models.CharField(max_length=16, null=True)),
                ('Desligado', models.IntegerField(null=True)),
                ('Ferias_inicio', models.DateTimeField(null=True)),
                ('Ferias_fim', models.DateTimeField(null=True)),
                ('Abono', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'dados',
                'managed': False,
            },
        ),
    ]
