# Generated by Django 4.1.7 on 2023-07-07 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mapeamento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mapeamento',
            options={'managed': False},
        ),
    ]
