# Generated by Django 4.1.7 on 2023-07-10 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_mapeamento_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mapeamento',
            table='mapeamento',
        ),
    ]
